extensions:
  # theme
  - ardonplay.jetbrains-idea-product-icon-theme
  - catppuccin.catppuccin-vsc-icons
  - github.github-vscode-theme
  # git
  - eamodio.gitlens
  # github
  - github.copilot
  - github.copilot-chat
  - github.vscode-github-actions
  - github.vscode-pull-request-github
  # docker
  - ms-azuretools.vscode-docker
  - docker.docker
  # k8s
  - ms-kubernetes-tools.vscode-kubernetes-tools
  # others
  - drcika.apc-extension
  - ms-vscode-remote.remote-containers
  - postman.postman-for-vscode
  - redhat.vscode-yaml
  - saoudrizwan.claude-dev
  - biomejs.biome
