set fileencodings=utf-8
set fenc=utf-8
autocmd InsertLeave *
set iminsert=0
set imsearch=0
set number
set expandtab
set tabstop=2
set shiftwidth=2
set smartindent
set backspace=indent,eol,start
set nobackup
set noswapfile
set autoread
set hidden
set showcmd
set cursorline
set virtualedit=onemore
set wrapscan
set hlsearch
set wildmenu
